Update to latest versions of dependencies and scala-2.12.x
precog/quasar pull request #4714
Opened 2020-11-10 18:37 UTC by wemrysi

2020-11-10 18:38 UTC, wemrysi commented
Breaking as the latest `shims` version seems to have affected implicit resolution in some situations.

2020-11-11 17:32 UTC, dcsobral requested changes
I'm not sure `Uri.uri("")` is deprecated -- I used a method like that at one point and it was, but there's a thousand ways to create an URI, and a dozen different URIs. If it is deprecated, I think it would be best to fix both deprecations at the same time.

I'll leave it as request changes. If you say that one isn't deprecated, consider it approved and merge it.

2020-11-11 17:32 UTC, dcsobral commented on impl/src/test/scala/quasar/impl/logging/ResponseBodyLoggingMiddlewareSpec.scala
> +        req <- GET(Uri.uri(""))
The deprecation warning recommends `uri""`.

2020-11-11 17:32 UTC, dcsobral commented on frontend/src/main/scala/quasar/frontend/logicalplan/Optimizer.scala
> +  private implicit def catsEvalScalazMonad[A] = shims.monadToScalaz[Eval]
I'm slightly concerned about the maintenance overload of all these private conversion definitions. Could this be fixed by unimporting something from a wildcard?

2020-11-11 17:32 UTC, dcsobral commented on project/Versions.scala
> +  val disciplineVersion   = "1.1.0"
On a personal note, I wish we would get rid of this file. I'm not entirely opposed to it, but I dislike very much having two ways of encoding versions across projects, particular on projects that are very active.

2020-11-11 17:34 UTC, wemrysi commented on project/Versions.scala
> +  val disciplineVersion   = "1.1.0"
Yeah, I'm not opposed to getting rid of it in favor of constants in `build.sbt`.

2020-11-11 17:40 UTC, wemrysi commented on impl/src/test/scala/quasar/impl/logging/ResponseBodyLoggingMiddlewareSpec.scala
> +        req <- GET(Uri.uri(""))
Oh, I completely overlooked that, we must have deprecation warnings disabled in tests as they aren't emitted. Anyhow, fixed.

2020-11-11 17:41 UTC, dcsobral approved these changes

2020-11-11 17:45 UTC, dcsobral commented on impl/src/test/scala/quasar/impl/logging/ResponseBodyLoggingMiddlewareSpec.scala
> +        req <- GET(Uri.uri(""))
There's a good reason to not have deprecation warnings on tests: if a library deprecates something, it still want to keep testing the deprecated code until it is removed.

2020-11-11 17:53 UTC, wemrysi commented on frontend/src/main/scala/quasar/frontend/logicalplan/Optimizer.scala
> +  private implicit def catsEvalScalazMonad[A] = shims.monadToScalaz[Eval]
Yeah, it isn't ideal, and I'm honestly not sure what exactly is causing the ambiguity (there are no `cats` implicit imports in this file) so this seemed the most explicit way of avoiding it.

Importing `shims._` does work, however it also quadruples the compile time which doesn't seem worth it to me and is why we try and avoid `import shims._` wherever we can.

2020-11-11 17:57 UTC, merged